Experiment - 2

In [2]:
# To understand the NumPy functions.
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# Print dimensions of array
print('The dimensions of arr are : ', arr.ndim)
# Print the shape of array
print('The shape of arr is : ', arr.shape)
# Print the datatype of array
print('The datatype of arr is : ', arr.dtype)

# Create a 2D array
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)
# Reshape an existing 1D array to 2D
arr3 = arr.reshape((4,2))
print(arr3)
# Dimensions and shape of 2D array
print('Dimension of arr2 is : ', arr2.ndim)
print('Shape of arr2 is : ', arr2.shape)

# Element wise multiplication
print(arr)
print(arr * 3)
# Element wise square of a numpy array
print(' ----- ')
print(arr)
print(arr ** 2)
# Multiplying a python list DOES NOT perform element wise multiplication
# Instead it creates duplicate copies for each element of list
print(' ----- ')
print([1, 2, 3] * 2)
# Change an element of numpy array
# Changes are reflected in reshaped numpy array also
print(arr)
arr[0] = 10
print(arr2)
print(arr3)

arr4 = arr.reshape(4,2).copy()
print(arr4)
# Changing contents of c does not change a because c is a copy of a
arr4[0][0] = 99
print(arr4)
print(arr)

# Print a specific element
print(arr[0])
# Print multiple elements at specific index 1 and 2
print(arr[np.array([1,2])])
# Print numpy array elements according to a condition
print('Even elements of arr are : ', arr[arr % 2 == 0])
# Conditional assignment of values
arr[arr == 10] = 12
print(arr)

The dimensions of arr are :  1
The shape of arr is :  (8,)
The datatype of arr is :  int64
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Dimension of arr2 is :  2
Shape of arr2 is :  (2, 3)
[1 2 3 4 5 6 7 8]
[ 3  6  9 12 15 18 21 24]
 ----- 
[1 2 3 4 5 6 7 8]
[ 1  4  9 16 25 36 49 64]
 ----- 
[1, 2, 3, 1, 2, 3]
[1 2 3 4 5 6 7 8]
[[1 2 3]
 [4 5 6]]
[[10  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]
[[10  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]
[[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]
[10  2  3  4  5  6  7  8]
10
[2 3]
Even elements of arr are :  [10  2  4  6  8]
[12  2  3  4  5  6  7  8]
