In [14]:
#Tic-Tac-Toe

import numpy as np
import random
from time import sleep

In [15]:
def create_board():
    return np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])

In [16]:
def possibilities(board):
    l = []
    for i in range(len(board)):
        for j in range(len(board)):
            if board[i][j] == 0:
                l.append((i, j))
    return l

In [17]:
def random_place(board, player):
    selection = possibilities(board)
    current_loc = random.choice(selection)
    board[current_loc] = player
    return board

In [18]:
def row_win(board, player):
    for x in range(len(board)):
        win = True
        for y in range(len(board)):
            if board[x, y] != player:
                win = False
                continue
        if win:
            return win
    return False

In [19]:
def col_win(board, player):
    for x in range(len(board)):
        win = True
        for y in range(len(board)):
            if board[y][x] != player:
                win = False
                continue
        if win:
            return win
    return False

In [20]:
def diag_win(board, player):
    win = True
    for x in range(len(board)):
        if board[x, x] != player:
            win = False
    if win:
        return win
    win = True
    for x in range(len(board)):
        y = len(board) - 1 - x
        if board[x, y] != player:
            win = False
    return win

In [21]:
def evaluate(board):
    winner = 0
    for player in [1, 2]:
        if (row_win(board, player) or
                col_win(board, player) or
                diag_win(board, player)):
            winner = player
            return winner
    if np.all(board != 0):
        winner = -1
    return winner

In [22]:
print("Winner is:" + str(play_game()))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after move 1
[[0 0 0]
 [0 0 1]
 [0 0 0]]
Board after move 2
[[0 0 2]
 [0 0 1]
 [0 0 0]]
Board after move 3
[[0 1 2]
 [0 0 1]
 [0 0 0]]
Board after move 4
[[0 1 2]
 [0 2 1]
 [0 0 0]]
Board after move 5
[[0 1 2]
 [0 2 1]
 [0 1 0]]
Board after move 6
[[0 1 2]
 [0 2 1]
 [0 1 2]]
Board after move 7
[[0 1 2]
 [1 2 1]
 [0 1 2]]
Board after move 8
[[0 1 2]
 [1 2 1]
 [2 1 2]]
Winner is:2
